### ISSUE TITLE
Running fcserver as non-root

### ISSUE THREAD

**Issue by reinzor** [scanlime/fadecandy#121]
I am running fcserver as root now, which works fine. However, when I try to execute it as non-root user, I do get permission errors. Anyone managed to run it as non-root user on linux using `udev` rules or adding to different groups? I tried `dialout` and `plugdev`.

**Comment by pvanassen** [comment]
Hi, 

I am using the following udev role to allow non-root users to run the server: 
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1d50", ATTRS{idProduct}=="607a", GROUP="users", MODE="0666"
```

**Comment by reinzor** [comment]
Thanks, I can verify that this works!
