### ISSUE TITLE
Command Line Not Accepting Alternate Configuration File

### ISSUE THREAD

**Issue by Mattjet27** [scanlime/fadecandy#47]
Hello,

I'm working with both a RaspberryPI and OSX, and I'm trying to get a project setup, which is similar to Phillip Burgess's NeoPixel Curtain Project. I am working with 3 fadecandy boards and am trying to pass the fadecady server a different configuration file to use so that I can properly map the LEDs I have in my project. However, I noticed (both with RPI and OSX) that whenever I try to run the server from the command line, as it says to in the help, fcserver [config.json], I get the following return:

"Error opening config file: No such file or directory"

This happens whether I am running from the relative directory I have both the sever and the JSON file in, or giving the command with absolute paths. I am new at this, so perhaps  I am doing something wrong. 

Can anyone tell me how I can get the server to use a different configuration file other than the default one? I can't seem to get this to work, and I'm hoping it's me and not a bug.

**Comment by scanlime** [comment]
I think this is an error in the command line syntax; discussion has moved to the FC mailing list.
