### ISSUE TITLE
Compiling on Ubuntu. 

### ISSUE THREAD

**Issue by rewolff** [scanlime/fadecandy#57]
I'm getting the impression that fadecandy server is out-of-sync with rapidjson. I pulled both from GIT and get lots of errors. 

After switching 
```
-#include "rapidjson/filestream.h"
+#include "rapidjson/filereadstream.h"
+#include "rapidjson/filewritestream.h"
```
and
```
-    size_t len = buffer.Size() - LWS_SEND_BUFFER_PRE_PADDING - LWS_SEND_BUFFER_POST_PADDING;
+    size_t len = buffer.GetSize() - LWS_SEND_BUFFER_PRE_PADDING - LWS_SEND_BUFFER_POST_PADDING;
```
I'm getting: 
```
error: no matching function for call to ‘rapidjson::GenericValue<rapidjson::UTF8<> >::AddMember(const char [5], const char*&, USBDevice::Allocator&)’
```

**Comment by scanlime** [comment]
Fadecandy isn't designed to build against arbitrary versions of rapidjson; it needs some modifications, which is why the git submodule pulls from https://github.com/scanlime/rapidjson.git
