### ISSUE TITLE
Rasberry pi / Examples

### ISSUE THREAD

**Issue by HUGEwindow** [scanlime/fadecandy#67]
I am using Raspberry Pi with Fadecandy. The server is running and it works via test patterns pulldown. My issue is that I am unable to get any of the examples to respond.  Any suggestions? 

Thanks in advance.

**Comment by M-I-Kessler** [comment]
Have you resolved this issue or are you still having problems?

**Comment by HUGEwindow** [comment]
My apologies. Fixed it. Thanks for checking up.  I can not remember the solve.  If I do I will add to post.

**Comment by M-I-Kessler** [comment]
For anyone else with this problem make sure you specify the WebSocket to the fcServer if you are not using a local instance.
`opc = new OPC(this, "127.0.0.1", 7890);`
Change the 127.0.0.1 to your fcServer's name.
